apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -uat
resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
labels:
  - includeSelectors: true
    pairs:
      variant: uat
patches:
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
