apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: biodiversityaudit-deployment-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: biodiversityaudit-deployment
      variant: uat
