apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: biodiversityaudit-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: biodiversity-audit.dbca.wa.gov.au
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: biodiversityaudit-clusterip-prod
                port:
                  number: 8080
