apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - ingress.yaml
  - pdb.yaml
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/biodiversityaudit2
    newTag: '1.0'
