apiVersion: apps/v1
kind: Deployment
metadata:
  name: biodiversityaudit-deployment
  labels:
    app: biodiversityaudit-deployment
spec:
  selector:
    matchLabels:
      app: biodiversityaudit-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: biodiversityaudit-deployment
    spec:
      containers:
      - name: biodiversityaudit
        image: ghcr.io/dbca-wa/biodiversityaudit2
        imagePullPolicy: Always
        env:
        - name: TZ
          value: "Australia/Perth"
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        startupProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 101
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: "Memory"
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
